name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: docs-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7

      - uses: ./.github/actions/build-docs
        with:
          subdir: dev

      - uses: ./.github/actions/deploy-to-gh-pages
        with:
          target: dev
          commit-message: Deploy dev docs
